# Generated by Django 4.1.7 on 2023-07-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
